### ISSUE TITLE
Unable to delete("drop database") with the admin user!

### ISSUE THREAD

**Issue by mbstacy** [cybercommons/cybercom-api#2]
API View: /api/data_store/data/

Action: 
           POST 
POST Content:
           {"action":"delete","database":"great_data"} 

Error:
{
    "Error": "command SON([('dropDatabase', 1)]) on namespace great_data.$cmd failed: not authorized on great_data to execute command { dropDatabase: 1 }"
}

@tdpearson I was looking at why this was causing an error. Found this but not sure where in your code that you are setting the role for the admin user. http://stackoverflow.com/questions/23943651/mongodb-admin-user-not-authorized

**Comment by tdpearson** [comment]
I am setting readWriteAnyDatabase role for the worker in the ../config/addmongouser script. If we need the worker to drop its database, we will need to change the assigned role.

**Comment by tdpearson** [comment]
Updated Mongo worker user to dbAdminAnyDatabse role.

**Comment by mbstacy** [comment]
Perfect lets call this issue closed.
